### ISSUE TITLE
Installation of version 2.3.3 fails

### ISSUE THREAD

**Issue by treiher** [Parquery/icontract#144]
```Console
% pip install icontract==2.3.3
Defaulting to user installation because normal site-packages is not writeable
Collecting icontract==2.3.3
  Using cached icontract-2.3.3.tar.gz (47 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-m15cfj1n/icontract/setup.py'"'"'; __file__='"'"'/tmp/pip-install-m15cfj1n/icontract/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-m15cfj1n/icontract/pip-egg-info
         cwd: /tmp/pip-install-m15cfj1n/icontract/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-m15cfj1n/icontract/setup.py", line 11, in <module>
        import icontract_meta
    ModuleNotFoundError: No module named 'icontract_meta'
```

**Comment by mristin** [comment]
Oh, my bad, I forgot to include it in `setup.py` and the precommit checks did not complain. I'll fix it tonight.

**Comment by treiher** [comment]
Thanks for the fast fix!
