### ISSUE TITLE
Invariant on subclass of NamedTuple produces TypeError

### ISSUE THREAD

**Issue by nyraghu** [Parquery/icontract#171]
An `invariant` decorator on a subclass of  `typing.NamedTuple` produces a `TypeError`.  Using Python 3.8.5 and icontract 2.3.7.

Example file `foo.py`:
``` python
from typing import NamedTuple
from icontract import invariant

@invariant(lambda self: self.first > 0)
class RightHalfPlanePoint(NamedTuple):
    first: int
    second: int

print(RightHalfPlanePoint(1, 0))
```

```
$ python foo.py 
Traceback (most recent call last):
  File "foo.py", line 9, in <module>
    print(RightHalfPlanePoint(1, 0))
  File "/tmp/foo/test-env/lib/python3.8/site-packages/icontract/_checkers.py", line 477, in wrapper
    result = func(*args, **kwargs)
TypeError: object.__init__() takes exactly one argument (the instance to initialize)
```

Disabling asssertions removes the error:
```
$ python -O foo.py 
RightHalfPlanePoint(first=1, second=0)
```

**Comment by mristin** [comment]
Hi @nyraghu ,
The PR #172 should have fixed it -- could you please test? I'll also test for dataclasses as soon as I get some time; they probably also break something.

**Comment by nyraghu** [comment]
> The PR #172 should have fixed it -- could you please test?

Many thanks! The version from master does fix the issue I had reported.

> I'll also test for dataclasses as soon as I get some time; they probably also break something.

Dataclasses were working alright even earlier, to the extent that I was using them.

Example file `test_foo.py`:
``` python
from dataclasses import dataclass
from icontract import ViolationError, invariant
from pytest import raises

@invariant(lambda self: self.first > 0)
@dataclass(frozen=True)
class RightHalfPlanePoint:
    first: int
    second: int

def test_conformance() -> None:
    RightHalfPlanePoint(1, 0)


def test_violation() -> None:
    with raises(ViolationError):
        RightHalfPlanePoint(0, 0)
```

```
$ pytest test_foo.py 
============================= test session starts ==============================
platform linux -- Python 3.8.5, pytest-6.1.2, py-1.9.0, pluggy-0.13.1
rootdir: /tmp/foo
collected 2 items                                                              

test_foo.py ..                                                           [100%]

============================== 2 passed in 0.06s ===============================
```

**Comment by mristin** [comment]
@nyraghu thanks! I added two tests just to avoid future regressions (see #173 ). Let's wait for another week for a release and hope more bugs resurface before :-).

**Comment by nyraghu** [comment]
Thanks again!
