### ISSUE TITLE
KeyError in contract caused by staticmethod and class invariant

### ISSUE THREAD

**Issue by treiher** [Parquery/icontract#186]
```Python
from icontract import invariant


@invariant(lambda self: all(" " not in part for part in self.parts))
class ID:
    def __init__(self, identifier: str) -> None:
        self.parts = identifier.split(self.separator())

    @staticmethod
    def separator() -> str:
        return "."


ID("A")
```

```Console
$ python test.py
Traceback (most recent call last):
  File "/tmp/venv/lib/python3.9/site-packages/icontract/_checkers.py", line 576, in wrapper
    instance = _find_self(param_names=param_names, args=args, kwargs=kwargs)
  File "/tmp/venv/lib/python3.9/site-packages/icontract/_checkers.py", line 499, in _find_self
    return kwargs["self"]
KeyError: 'self'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/tmp/test.py", line 14, in <module>
    ID("A")
  File "/tmp/venv/lib/python3.9/site-packages/icontract/_checkers.py", line 561, in wrapper
    result = func(*args, **kwargs)
  File "/tmp/test.py", line 7, in __init__
    self.parts = identifier.split(self.separator())
  File "/tmp/venv/lib/python3.9/site-packages/icontract/_checkers.py", line 578, in wrapper
    raise KeyError(("The parameter 'self' could not be found in the call to function {!r}: "
KeyError: "The parameter 'self' could not be found in the call to function <function ID.separator at 0x7f26061a1550>: the param names were [], the args were (<__main__.ID object at 0x7f260636beb0>,) and kwargs were {}"
```

### Versions

```
icontract  2.4.1
asttokens  2.0.4
Python     3.9.1
```

**Comment by mristin** [comment]
Hi @treiher ,
Thanks for the report! I'll have a look at it during the weekend. (I even thought I tested for this case, but I probably forgot.)

**Comment by mristin** [comment]
Hi @treiher ,
Could you please check that #187 fixes your problem before I merge it in? (When originally writing the library, I handled `classmethod`s, but forgot to come back and handle the `staticmethod`s.)

**Comment by treiher** [comment]
The code of #187 works for my use case. Thanks for fixing!
